### ISSUE TITLE
doesn't work on ubuntu 13.10

### ISSUE THREAD

**Issue by blaze33** [cas--/indicator-usb#1]
Just for the record as this issue is solved:

indicator-usb seemed to do nothing after being launched. I made sure to `rm ~/.config/indicator-usb`, actually mount an usb pen drive and relaunched indicator-usb and just noticed it worked.

Not sure if something was wrong, just be aware that indicator-usb does not display an icon if no external volume is mounted.

Thanks :)

**Comment by cas--** [comment]
I think this was the intention of the original implementation, it runs in the background and it will only show up as an indicator when you need to unmount a volume.
